create table if not exists public.catalog_categories (
  id text primary key,
  name text not null,
  icon text not null default '',
  description text not null default '',
  sort_order integer not null default 0,
  status text not null default 'active' check (status in ('active', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.catalog_products (
  id text primary key,
  category_id text not null references public.catalog_categories(id) on delete restrict,
  name text not null,
  description text not null default '',
  unit text not null default 'un',
  group_label text,
  no_photo boolean not null default false,
  sizes text[] not null default '{}',
  material text,
  finish text,
  norm text,
  standard_length text,
  applications text[] not null default '{}',
  sort_order integer not null default 0,
  status text not null default 'active' check (status in ('active', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.services (
  id text primary key,
  name text not null,
  description text not null default '',
  price_note text not null default '',
  highlight text not null default '',
  sort_order integer not null default 0,
  status text not null default 'active' check (status in ('active', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.media_assets (
  id bigint generated by default as identity primary key,
  storage_bucket text not null default 'website-media',
  storage_path text not null,
  public_url text not null,
  file_name text not null,
  mime_type text not null,
  width integer,
  height integer,
  alt text not null default '',
  status text not null default 'active' check (status in ('active', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.entity_images (
  id bigint generated by default as identity primary key,
  entity_type text not null check (entity_type in ('category', 'product', 'service')),
  entity_id text not null,
  media_asset_id bigint not null references public.media_assets(id) on delete restrict,
  role text not null check (role in ('main', 'gallery')),
  sort_order integer not null default 0,
  status text not null default 'active' check (status in ('active', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.image_variants (
  id bigint generated by default as identity primary key,
  entity_image_id bigint not null references public.entity_images(id) on delete cascade,
  placement text not null check (placement in ('category_card', 'product_card', 'product_detail', 'service_card', 'service_banner')),
  storage_bucket text not null default 'website-media',
  storage_path text not null,
  public_url text not null,
  crop jsonb not null default '{}'::jsonb,
  width integer,
  height integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (entity_image_id, placement)
);

create index if not exists catalog_products_category_order_idx on public.catalog_products(category_id, sort_order);
create unique index if not exists media_assets_storage_path_uidx on public.media_assets(storage_bucket, storage_path);
create index if not exists entity_images_lookup_idx on public.entity_images(entity_type, entity_id, role, status, sort_order);
create index if not exists image_variants_entity_idx on public.image_variants(entity_image_id, placement);

insert into storage.buckets (id, name, public)
values ('website-media', 'website-media', true)
on conflict (id) do nothing;
