export const COMPANY_INFO = {
  name: "JRS Ferros",
  address: "Av. Principal 183, 4535-014 Lourosa, Portugal",
  addressDisplay: "Av. Principal 183, 4535-014 Lourosa, Portugal",
  phoneWarehouse: "+351 22 764 3124",
  mobileWarehouse: "+351 917 322 797",
  email: "geral@jrsferros.pt",
  tagline: "Qualidade com Tradição",
  mapsUrl: "https://www.google.com/maps/search/?api=1&query=JRS%20Ferros%20Av.%20Principal%20183%204535-014%20Lourosa%20Portugal",
  facebookUrl: "",
  linkedinUrl: "",
  nif: "",
};

export interface SubCategory {
  id: string;
  name: string;
  description: string;
  image: string;
  unit: string;
  sizes: string[];
  group?: string;   // visual section header within a category page
  noPhoto?: boolean; // true for very specific products that don't need a photo
}

export interface ProductCategory {
  id: string;
  name: string;
  icon: string;
  description: string;
  image: string;
  subcategories: SubCategory[];
}

export interface ServiceItem {
  id: string;
  name: string;
  description: string;
  image: string;
  priceNote: string;
  highlight: string;
}

export const CATALOG: ProductCategory[] = [
  {
    id: "barras",
    name: "Barras de Aço",
    icon: "━",
    description: "Barras de aço maciças em diversas secções e medidas.",
    image: "/imagensferros/ferroscilindercloseup.jpeg",
    subcategories: [
      {
        id: "barra-quadrada",
        name: "Barra Quadrada",
        description: "Barra de aço de secção quadrada para serralharia e construção.",
        image: "/images/barra-quadrada.jpeg",
        unit: "kg",
        sizes: ["6 mm", "8 mm", "10 mm", "12 mm", "16 mm", "20 mm", "25 mm", "30 mm", "40 mm", "50 mm", "70 mm"],
      },
      {
        id: "barra-rectangular",
        name: "Barra Rectangular",
        description: "Barra de aço de secção rectangular, amplamente usada em construção metálica.",
        image: "/images/barra-retangular.jpeg",
        unit: "kg",
        sizes: [
          "12×3", "12×4", "12×5",
          "15×5",
          "16×3", "16×5",
          "20×3", "20×5", "20×6", "20×8", "20×10", "20×12",
          "25×3", "25×5", "25×6", "25×8", "25×10", "25×12",
          "30×3", "30×5", "30×6", "30×8", "30×10", "30×12", "30×15",
          "35×5", "35×6", "35×8", "35×10",
          "40×3", "40×5", "40×6", "40×8", "40×10", "40×12", "40×15", "40×20",
          "45×5", "45×6", "45×8", "45×10", "45×12",
          "50×5", "50×6", "50×8", "50×10", "50×12", "50×15", "50×20", "50×25",
          "60×5", "60×6", "60×8", "60×10", "60×12", "60×15", "60×20", "60×25",
          "70×6", "70×8", "70×10", "70×12", "70×15", "70×20",
          "80×6", "80×8", "80×10", "80×12", "80×15", "80×20", "80×25",
          "90×10", "90×15",
          "100×6", "100×8", "100×10", "100×12", "100×15", "100×20", "100×25",
          "120×8", "120×10", "120×12", "120×15", "120×20", "120×25",
          "140×10", "140×12", "140×15", "140×20",
          "150×8", "150×10", "150×12", "150×15", "150×20", "150×25",
          "160×10", "160×12", "160×15", "160×20",
          "180×10", "180×12", "180×15", "180×20",
          "200×8", "200×10", "200×12", "200×15", "200×20", "200×25", "200×30",
          "220×10", "220×15", "220×20",
          "250×10", "250×12", "250×15", "250×20", "250×25",
          "300×10", "300×12", "300×15", "300×20", "300×25", "300×30",
          "350×10", "350×15",
          "400×10", "400×12", "400×20",
        ],
      },
      {
        id: "barra-t",
        name: "Barra T",
        description: "Barra de aço com perfil em T para reforço estrutural.",
        image: "/images/barra-t.jpeg",
        unit: "kg",
        sizes: ["T 20", "T 25", "T 30", "T 35", "T 40", "T 45", "T 50", "T 60", "T 70", "T 80", "T 100"],
      },
      {
        id: "barra-u",
        name: "Barra U",
        description: "Barra de aço com perfil em U para caleiras e reforços.",
        image: "/images/barra-u.jpeg",
        unit: "kg",
        sizes: ["30×15×4", "40×20×5", "40×35×5", "50×25×5", "50×38×5", "60×30×6", "65×42×5,5"],
      },
      {
        id: "varao-redondo-serralharia",
        name: "Varão Redondo p/ Serralharia",
        description: "Varão de aço de secção circular para serralharia e estruturas metálicas.",
        image: "/images/varao-redondo.jpeg",
        unit: "kg",
        sizes: ["6 mm", "8 mm", "10 mm", "12 mm", "16 mm", "20 mm", "25 mm", "30 mm", "32 mm", "35 mm", "40 mm", "50 mm", "55 mm", "60 mm", "65 mm", "80 mm", "100 mm"],
      },
    ],
  },
  {
    id: "perfis",
    name: "Perfis Estruturais",
    icon: "I",
    description: "Vigas e perfis laminados a quente para estruturas metálicas.",
    image: "/imagensferros/piledstacks.jpeg",
    subcategories: [
      {
        id: "hea",
        name: "Ferro HEA",
        description: "Viga de duplo T de aba larga, série A. Ideal para estruturas de betão armado e metálicas.",
        image: "/images/perfil-hea.jpeg",
        unit: "kg",
        sizes: ["HEA 100", "HEA 120", "HEA 140", "HEA 160", "HEA 180", "HEA 200", "HEA 220", "HEA 240", "HEA 260", "HEA 280", "HEA 300"],
      },
      {
        id: "heb",
        name: "Ferro HEB",
        description: "Viga de duplo T de aba larga, série B. Maior resistência e capacidade de carga.",
        image: "/images/perfil-heb.jpeg",
        unit: "kg",
        sizes: ["HEB 100", "HEB 120", "HEB 140", "HEB 160", "HEB 180", "HEB 200", "HEB 220", "HEB 240", "HEB 260", "HEB 280", "HEB 300", "HEB 320", "HEB 340", "HEB 360", "HEB 400"],
      },
      {
        id: "ipe",
        name: "Ferro IPE",
        description: "Viga de duplo T de aba estreita. O perfil mais utilizado em estruturas metálicas.",
        image: "/images/perfil-ipe.jpeg",
        unit: "kg",
        sizes: ["IPE 80", "IPE 100", "IPE 120", "IPE 140", "IPE 160", "IPE 180", "IPE 200", "IPE 220", "IPE 240", "IPE 270", "IPE 300", "IPE 330", "IPE 360", "IPE 400"],
      },
      {
        id: "ipn",
        name: "Ferro IPN",
        description: "Viga em I de aba inclinada. Utilizada em vigas e travessas.",
        image: "/imagensferros/piledstacks2.jpeg",
        unit: "kg",
        sizes: ["IPN 100", "IPN 140", "IPN 160", "IPN 180", "IPN 200", "IPN 220", "IPN 240", "IPN 260", "IPN 280", "IPN 320", "IPN 360"],
      },
      {
        id: "upn",
        name: "Ferro UPN",
        description: "Perfil em U de aba inclinada. Para vigas de suporte, guias e reforços.",
        image: "/images/perfil-upn.jpeg",
        unit: "kg",
        sizes: ["UPN 80", "UPN 100", "UPN 120", "UPN 140", "UPN 160", "UPN 180", "UPN 200", "UPN 220", "UPN 240", "UPN 260", "UPN 280", "UPN 300", "UPN 320"],
      },
    ],
  },
  {
    id: "cantoneiras",
    name: "Cantoneiras",
    icon: "L",
    description: "Cantoneiras de aço iguais e desiguais para construção e serralharia.",
    image: "/imagensferros/ferroscloseup5.jpeg",
    subcategories: [
      {
        id: "cantoneira-igual",
        name: "Cantoneira Igual",
        description: "Cantoneira de aço com abas iguais. Muito versátil para reforços e estruturas.",
        image: "/images/cantoneiras-de-abas-iguais.jpeg",
        unit: "kg",
        sizes: [
          "15×15×3", "20×20×3", "20×20×4",
          "25×25×3", "25×25×5",
          "30×30×3", "30×30×4", "30×30×5",
          "35×35×3", "35×35×4", "35×35×5",
          "40×40×4", "40×40×5",
          "45×45×5",
          "50×50×5", "50×50×6",
          "60×60×5", "60×60×6",
          "70×70×7",
          "80×80×8",
          "90×90×9",
          "100×100×10",
          "120×120×12",
          "150×150×15",
          "200×200×20",
        ],
      },
      {
        id: "cantoneira-desigual",
        name: "Cantoneira Desigual",
        description: "Cantoneira de aço com abas de diferentes dimensões.",
        image: "/images/cantoneiras-abas-desiguais.jpeg",
        unit: "kg",
        sizes: ["45×30×5", "50×30×5", "50×40×5", "60×30×5", "60×40×6"],
      },
    ],
  },
  {
    id: "tubos",
    name: "Tubos",
    icon: "○",
    description: "Tubos de aço pretos, galvanizados, quadrados, retangulares, redondos e séries técnicas.",
    image: "/produtos/tubos_quadrados.png",
    subcategories: [
      {
        id: "tubo-quadrado-preto",
        name: "Tubo Quadrado Preto",
        description: "Tubo de aço de secção quadrada sem tratamento superficial.",
        image: "/images/tubo-quadrado-preto.jpeg",
        unit: "mt",
        group: "Tubos Quadrados",
        sizes: [
          "12×12×1,5", "16×16×1,5", "20×20×1,5", "20×20×2",
          "25×25×1,5", "25×25×2",
          "30×30×1,5", "30×30×2", "30×30×3",
          "35×35×1,5", "35×35×2",
          "40×40×1,5", "40×40×2", "40×40×3", "40×40×4",
          "45×45×1,5",
          "50×50×1,5", "50×50×2", "50×50×3", "50×50×4",
          "60×60×1,5", "60×60×2", "60×60×3", "60×60×5",
          "70×70×2", "70×70×4",
          "80×40×4", "80×80×2", "80×80×3", "80×80×4", "80×80×5",
          "100×100×2", "100×100×3", "100×100×4",
          "120×120×3", "120×120×4",
          "150×150×4",
          "200×200×4",
          "250×250×5",
        ],
      },
      {
        id: "tubo-quadrado-galv",
        name: "Tubo Quadrado Galvanizado",
        description: "Tubo de aço de secção quadrada com tratamento galvanizado.",
        image: "/images/tubo-quadrado-galvanizado.jpeg",
        unit: "mt",
        group: "Tubos Quadrados",
        sizes: [
          "20×20×1,5", "25×25×1,5",
          "30×30×1,5", "30×30×2",
          "35×35×1,5",
          "40×40×1,5", "40×40×2",
          "45×45×1,5",
          "50×50×1,5", "50×50×2",
          "60×60×1,5", "60×60×2",
          "80×80×2",
          "100×100×2",
        ],
      },
      {
        id: "tubo-rectangular-preto",
        name: "Tubo Rectangular Preto",
        description: "Tubo de aço de secção rectangular sem tratamento superficial.",
        image: "/images/tubo-retangular-preto.jpeg",
        unit: "mt",
        group: "Tubos Retangulares",
        sizes: [
          "25×15×1,5",
          "30×15×1,5", "30×20×1,5",
          "35×20×1,5",
          "40×10×1,5", "40×15×1,5", "40×20×1,5", "40×20×2", "40×25×1,5", "40×30×1,5", "40×30×2",
          "50×10×1,5", "50×15×1,5", "50×20×1,5", "50×20×2", "50×25×1,5", "50×30×1,5", "50×30×2", "50×30×3", "50×40×1,5", "50×40×2",
          "60×10×1,5", "60×20×1,5", "60×20×2", "60×30×1,5", "60×30×2", "60×30×3", "60×40×1,5", "60×40×2", "60×40×3", "60×40×4",
          "70×30×2",
          "80×20×1,5", "80×20×2", "80×30×2", "80×40×1,5", "80×40×2", "80×40×3", "80×60×2",
          "100×20×2", "100×40×2", "100×40×3", "100×50×2", "100×50×3", "100×50×4", "100×60×2", "100×60×3", "100×60×4", "100×80×4",
          "120×40×2", "120×60×2", "120×60×4", "120×80×5",
          "150×50×3", "150×100×5",
          "160×80×3", "160×80×5",
          "200×100×4",
        ],
      },
      {
        id: "tubo-rectangular-galv",
        name: "Tubo Rectangular Galvanizado",
        description: "Tubo de aço de secção rectangular com tratamento galvanizado.",
        image: "/images/tubo-retangular-galvanizado.jpeg",
        unit: "mt",
        group: "Tubos Retangulares",
        sizes: [
          "20×10×1,5",
          "30×15×1,5", "30×20×1,5",
          "40×20×1,5", "40×30×1,5",
          "50×30×1,5", "50×30×2", "50×40×1,5",
          "60×20×1,5", "60×30×1,5", "60×30×2", "60×40×1,5", "60×40×2",
          "80×40×1,5", "80×40×2",
          "100×40×2", "100×50×2",
          "120×60×2",
        ],
      },
      {
        id: "tubo-redondo-preto",
        name: "Tubo Redondo Preto",
        description: "Tubo de aço de secção circular sem tratamento superficial.",
        image: "/images/tubo-redondo-preto.jpeg",
        unit: "mt",
        group: "Tubos Redondos",
        sizes: [
          "10×1,5", "12×1,5", "20×1,5", "20×2", "22×1,5",
          "25×1,5", "25×2", "28×1,5", "28×2",
          "30×1,5", "30×2", "32×1,5", "32×2",
          "35×1,5", "35×2", "38×1,5", "38×2",
          "40×1,5", "40×2", "42×1,5", "42×2",
          "45×1,5", "45×2", "48×1,5", "48×2",
          "50×1,5", "50×2", "55×1,5",
          "60×1,5", "60×2", "65×3",
          "70×2", "76×2", "80×2", "80×3",
          "100×2", "120×3", "200×4",
        ],
      },
      {
        id: "tubo-redondo-galv",
        name: "Tubo Redondo Galvanizado",
        description: "Tubo de aço de secção circular com tratamento galvanizado.",
        image: "/images/tubo-redondogalvanizado.jpeg",
        unit: "mt",
        group: "Tubos Redondos",
        sizes: [
          "16×1,5", "20×1,5", "25×1,5", "30×1,5",
          "35×1,5", "40×1,5", "45×1,5", "48×1,5",
          "50×1,5", "50×2", "60×1,5", "80×2",
        ],
      },
      {
        id: "tubo-galv-ligeira",
        name: "Tubo Galv. Série Ligeira",
        description: "Tubo de aço galvanizado com rosca, série ligeira. Para instalações e condutas.",
        image: "/images/tubo-galvanizado-seriemedia-e-serieligeira.jpeg",
        unit: "mt",
        group: "Tubos Série Ligeira",
        sizes: ['3/8"', '1/2"', '3/4"', '1"', '1.1/4"', '1.1/2"', '2"', '2.1/2"', '3"', '3.1/2"'],
      },
      {
        id: "tubo-galv-media",
        name: "Tubo Galv. Série Média",
        description: "Tubo de aço galvanizado com rosca, série média. Maior resistência à pressão.",
        image: "/images/tubo-galvanizado-seriemedia-e-serieligeira.jpeg",
        unit: "mt",
        group: "Tubos Série Média",
        sizes: ['1/2"', '3/4"', '1"', '1.1/4"', '1.1/2"', '2"', '2.1/2"', '3"', '3.1/2"', '4"', '5"', '6"'],
      },
      {
        id: "tubo-preto-ligeira",
        name: "Tubo Preto Série Ligeira",
        description: "Tubo de aço preto com rosca, série ligeira.",
        image: "/images/tubo-redondo-preto-serieligeira.jpeg",
        unit: "mt",
        group: "Tubos Série Ligeira",
        sizes: ['3/8"', '1/2"', '3/4"', '1"', '1.1/4"', '1.1/2"', '2"', '2.1/2"', '3"', '3.1/2"', '4"'],
      },
      {
        id: "tubo-preto-media",
        name: "Tubo Preto Série Média",
        description: "Tubo de aço preto com rosca, série média.",
        image: "/images/tubo-redondo-preto-seriemedia.jpeg",
        unit: "mt",
        group: "Tubos Série Média",
        sizes: ['1/2"', '3/4"', '1"', '1.1/4"', '1.1/2"', '2"', '2.1/2"', '3"', '3.1/2"', '4"', '5"', '6"'],
      },
      {
        id: "tubo-ft-preto",
        name: "Tubo FT (com Abas) Preto",
        description: "Tubo FT preto com abas para fixação em sistemas de vedação e estruturas metálicas.",
        image: "/images/tubo-ft-com-abas.jpeg",
        unit: "mt",
        group: "Tubos FT (com abas) Preto",
        sizes: [
          "FT 12 Preto 2 Abas", "FT 15 Preto 1 Aba",
          "FT 16 Preto 2 Abas", "FT 17 Preto 1 Aba",
          "FT 19 Preto 1 Aba",
          "FT 21 Preto 2 Abas", "FT 27 Preto 2 Abas",
        ],
      },
      {
        id: "tubo-ft-galv",
        name: "Tubo FT (com Abas) Galvanizado",
        description: "Tubo FT galvanizado com abas para fixação, indicado para aplicações exteriores e vedações.",
        image: "/images/tubo-ft-com-abas.jpeg",
        unit: "mt",
        group: "Tubos FT (com abas) Galvanizado",
        sizes: [
          "FT 14 Galv. 1 Aba",
          "FT 15 Galv. 1 Aba",
          "FT 19 Galv. 1 Aba",
        ],
      },
      {
        id: "tubo-calhe-preto",
        name: "Tubo de Calhe Preto",
        description: "Tubo de calha preto para portões e sistemas de guia. Séries Apolo e U.",
        image: "/imagensferros/ferroswide.jpeg",
        unit: "kg",
        group: "Tubos de Calhe Pretos",
        noPhoto: true,
        sizes: [
          "Apolo F73 Preto",
          "Apolo F74 Preto", "Apolo F76 Preto",
          "U Preta 60", "U Preta 70", "U Preta 80", "U Preta 90", "U Preta 100",
        ],
      },
      {
        id: "tubo-calhe-galv",
        name: "Tubo de Calhe Galvanizado",
        description: "Tubo de calha galvanizado para portões e sistemas de guia com maior resistência à corrosão.",
        image: "/imagensferros/ferroswide.jpeg",
        unit: "kg",
        group: "Tubos de Calhe Galvanizados",
        noPhoto: true,
        sizes: [
          "Apolo F73 Galv.",
          "Apolo F74 Galv.",
        ],
      },
      {
        id: "tubo-corrimao",
        name: "Tubo Corrimão",
        description: "Tubo especial para corrimãos e guardas de escadas.",
        image: "/images/tubo-corrimao.jpeg",
        unit: "mt",
        group: "Outros Tubos",
        sizes: ["Corrimão 223"],
      },
      {
        id: "curvas-tubo",
        name: "Curvas de Tubo",
        description: "Curvas e cotovelos para tubagem de aço.",
        image: "/images/curvas-de-tubo.jpeg",
        unit: "un",
        group: "Outros Tubos",
        sizes: ['1/2"', '3/4"', '1"', '1.1/4"', '1.1/2"', '2"', '2.1/2"', '3"', '3.1/2"', '4"', '5"', '6"', '8"'],
      },
    ],
  },
  {
    id: "chapas",
    name: "Chapas",
    icon: "▬",
    description: "Chapas de aço, galvanizadas, onduladas, xadrez, zincor e fibra de vidro.",
    image: "/produtos/chapas.png",
    subcategories: [
      {
        id: "chapa-preta",
        name: "Chapa Preta",
        description: "Chapa de aço laminada a quente para construção e serralharia.",
        image: "/images/chapa-preta.jpeg",
        unit: "kg",
        sizes: ["1,5 mm", "2 mm", "2,5 mm", "3 mm", "4 mm", "5 mm", "6 mm", "8 mm", "10 mm", "12 mm", "16 mm", "20 mm", "25 mm", "30 mm", "35 mm", "40 mm"],
      },
      {
        id: "chapa-gotas",
        name: "Chapa de Gotas (Preta)",
        description: "Chapa de aço com relevo em gota para pisos e plataformas anti-derrapantes.",
        image: "/images/chapa-preta-de-gota.jpeg",
        unit: "kg",
        sizes: ["3 mm", "4 mm", "5 mm"],
      },
      {
        id: "chapa-xadrez",
        name: "Chapa Xadrez (Preta)",
        description: "Chapa de aço com relevo xadrez anti-derrapante para pisos e escadas.",
        image: "/images/chapa-preta-xadrez.jpeg",
        unit: "kg",
        sizes: ["3 mm", "4 mm", "5 mm", "6 mm"],
      },
      {
        id: "chapa-galv-lisa",
        name: "Chapa Galvanizada Lisa",
        description: "Chapa de aço galvanizada de superfície lisa para coberturas e revestimentos.",
        image: "/imagensferros/ferroscloseup.jpeg",
        unit: "kg",
        sizes: ["0,40 mm", "0,50 mm", "0,60 mm", "0,80 mm", "1,00 mm", "1,25 mm", "1,50 mm", "2,00 mm", "2,50 mm", "3,00 mm"],
      },
      {
        id: "chapa-galv-ondulada",
        name: "Chapa Galvanizada Ondulada",
        description: "Chapa de aço galvanizada com perfil ondulado para coberturas e vedações.",
        image: "/images/chapa-galvanizada-ondulada.jpeg",
        unit: "kg",
        sizes: ["2,0 m", "2,5 m", "3,0 m", "3,5 m", "4,0 m", "4,5 m", "5,0 m", "5,5 m", "6,0 m"],
      },
      {
        id: "chapa-zincor",
        name: "Chapa Zincor",
        description: "Chapa de aço revestida com liga de zinco-alumínio. Alta resistência à corrosão.",
        image: "/images/chapa-zincor.jpeg",
        unit: "kg",
        sizes: ["0,80 mm", "1,00 mm", "1,25 mm", "1,50 mm", "2,00 mm", "3,00 mm"],
      },
      {
        id: "chapa-zinco-vermelha",
        name: "Chapa Zinco Vermelha",
        description: "Chapa de zinco com acabamento vermelho para coberturas decorativas.",
        image: "/imagensferros/ferrospiledup.jpeg",
        unit: "kg",
        noPhoto: true,
        sizes: ["3 m", "4 m", "5 m", "6 m"],
      },
      {
        id: "chapa-canelada",
        name: "Chapa Canelada",
        description: "Chapa canelada Nº 26 para coberturas e revestimentos.",
        image: "/images/chapa-canelada.jpeg",
        unit: "un",
        sizes: ["2,0 m", "2,5 m"],
      },
      {
        id: "chapa-antiderrapante-alum",
        name: "Chapa Anti-derrapante Alumínio",
        description: "Chapa de alumínio com superfície anti-derrapante para escadas e pisos.",
        image: "/images/chapa-antiderrapante-aluminio.jpeg",
        unit: "un",
        sizes: ["Standard"],
      },
      {
        id: "chapa-fibra-vidro",
        name: "Chapa Fibra de Vidro",
        description: "Chapa translúcida de fibra de vidro para coberturas e claraboias.",
        image: "/images/chapa-fibra-de-vidro.jpeg",
        unit: "un",
        sizes: ["2,00×1,15 m", "2,50×1,15 m", "3,00×1,15 m", "3,50×1,15 m", "4,00×1,15 m", "4,50×1,15 m", "5,00×1,15 m", "5,50×1,15 m", "6,00×1,15 m", "Lisa (por metro)"],
      },
    ],
  },
  {
    id: "construcao-civil",
    name: "Construção Civil",
    icon: "⬛",
    description: "Varão para betão armado, malhas electrosoldadas e materiais de construção.",
    image: "/produtos/varao_betao.png",
    subcategories: [
      {
        id: "varao-betao-a500",
        name: "Varão p/ Betão",
        description: "Varão de aço nervurado para armaduras de betão armado de alta resistência. Serviço de corte para Vigas disponível.",
        image: "/images/varao-para-betao.jpeg",
        unit: "kg",
        sizes: ["NR 6", "NR 8", "NR 10", "NR 12", "NR 16", "NR 20", "NR 25", "NR 32"],
      },
      {
        id: "malhasol",
        name: "Malha Sol (Electrosoldada)",
        description: "Malha de aço electrosoldada para reforço de lajes, pavimentos e muros.",
        image: "/images/malha-sol.jpeg",
        unit: "m²",
        sizes: ["AR34 Rolo", "CQ30 Rolo", "CQ38 Rolo", "CQ30 Meio Rolo", "FND40 Painel", "FND50 Painel", "FND60 Painel", "FND70 Painel", "FND80 Painel", "FND100 Painel", "FNQ50 Painel"],
      },
      {
        id: "cimento",
        name: "Cimento",
        description: "Cimento para obras de construção civil.",
        image: "/images/cimento.jpeg",
        unit: "un",
        sizes: ["Saco 25 kg", "Saco 50 kg"],
      },
      {
        id: "arame-recozido",
        name: "Arame Recozido",
        description: "Arame recozido para amarrações e trabalhos de construção civil.",
        image: "/images/arame-recozido.jpeg",
        unit: "kg",
        sizes: ["130"],
      },
      {
        id: "pregos-construcao-civil",
        name: "Pregos",
        description: "Pregos para fixação em obra, cofragens e trabalhos gerais de construção civil.",
        image: "/images/pregos.jpeg",
        unit: "kg",
        sizes: ["Standard"],
      },
    ],
  },
  {
    id: "acessorios",
    name: "Acessórios e Ferragens",
    icon: "⚙",
    description: "Rodízios, roldanas, tampas, grelhas, fixações e outros acessórios para serralharia.",
    image: "/imagensferros/inventoryworkplace.jpeg",
    subcategories: [
      {
        id: "gradil-galv",
        name: "Gradil Galvanizado",
        description: "Painel de malha de arame galvanizado para vedações e grades.",
        image: "/images/gradilgalvanizado.jpeg",
        unit: "un",
        group: "Grelhas",
        sizes: ["500×1000 mm", "1000×1000 mm", "1500×1000 mm", "2000×1000 mm"],
      },
      {
        id: "grelha-quad-galv",
        name: "Grelha Quadrada c/Aro Galv.",
        description: "Grelha quadrada com aro galvanizado para sumidouros e caleiras.",
        image: "/images/grelhaquadradocomarogalvanizado.jpeg",
        unit: "un",
        group: "Grelhas",
        sizes: ["400×25 mm", "500×25 mm", "600×25 mm"],
      },
      {
        id: "grelha-transito-ligeiro",
        name: "Grelha Trânsito Ligeiro",
        description: "Grelha para passagem de trânsito ligeiro em caleiras e sumidouros.",
        image: "/images/grelhatransitoligeiro.jpeg",
        unit: "un",
        group: "Grelhas",
        sizes: ["40×10 cm", "40×15 cm", "40×20 cm", "40×25 cm"],
      },
      {
        id: "grelha-transito-pesado",
        name: "Grelha Trânsito Pesado",
        description: "Grelha reforçada para passagem de trânsito pesado.",
        image: "/images/grelhatransitopesado.jpeg",
        unit: "un",
        group: "Grelhas",
        sizes: ["40×15 cm", "40×20 cm", "40×25 cm"],
      },
      {
        id: "rodizios",
        name: "Rodízios",
        description: "Rodízios para portões, grades e estruturas deslizantes.",
        image: "/imagensferros/inventoryworkplace.jpeg",
        unit: "un",
        group: "Portões e Vedação",
        sizes: [
          "Guia Nylon Grande", "Guia Nylon Pequeno",
          "Grandes Duplos", "Grandes Simples",
          "Guia Super C/Afinad 212",
          "Médios Duplos - 35D", "Médios Simples - 35S",
        ],
      },
      {
        id: "roldanas",
        name: "Roldanas",
        description: "Roldanas com e sem aro para sistemas de portões e guias.",
        image: "/imagensferros/inventoryworkplace.jpeg",
        unit: "un",
        group: "Portões e Vedação",
        noPhoto: true,
        sizes: [
          "Ø60 sem aro",
          "Ø75 com aro", "Ø75 sem aro",
          "Ø90 com aro", "Ø90 sem aro",
          "Ø100 com aro", "Ø100 sem aro",
          "Ø120 com aro", "Ø120 sem aro",
        ],
      },
      {
        id: "tampas",
        name: "Tampas",
        description: "Tampas de fecho para tubos quadrados, rectangulares e redondos.",
        image: "/imagensferros/inventoryworkplace.jpeg",
        unit: "un",
        group: "Portões e Vedação",
        noPhoto: true,
        sizes: [
          "Encher Galv. 40×40×5", "Encher Galv. 40×40×7,5",
          "Encher Galv. 50×50×5", "Encher Galv. 50×50×7,5",
          "Encher Galv. 60×60×5", "Encher Galv. 60×60×7,5",
          "S. Encher 33", "S. Encher 40", "S. Encher 50", "S. Encher 60",
          "S. Lisas 50", "S. Lisas 60",
        ],
      },
      {
        id: "olhais",
        name: "Olhais",
        description: "Olhais de fixação em diversas dimensões.",
        image: "/images/olhais.jpeg",
        unit: "un",
        group: "Fixações e Ferragens",
        sizes: ["820 — 50×11", "820 — 90×18", "820 — 100×20", "820 — 120×20", "Enrolados 3/8", "Enrolados 5/8"],
      },
      {
        id: "carros-portao",
        name: "Carros para Portão",
        description: "Carros de deslizamento para portões corredores duplos e simples.",
        image: "/imagensferros/inventoryworkplace.jpeg",
        unit: "un",
        group: "Portões e Vedação",
        noPhoto: true,
        sizes: ["Duplos — 10", "Simples — 12", "Simples Pequenos"],
      },
      {
        id: "fechos-serralheiro",
        name: "Fechos Serralheiro",
        description: "Fechos de serralheiro para grades e portões.",
        image: "/images/fechosserralheiro.jpeg",
        unit: "un",
        group: "Portões e Vedação",
        sizes: ["3/8 × 1 Palmo", "3/8 × 1,5 Palmo"],
      },
      {
        id: "fechaduras",
        name: "Fechaduras",
        description: "Fechaduras normais e eléctricas para portões e grades.",
        image: "/images/fechaduras.jpeg",
        unit: "un",
        group: "Portões e Vedação",
        sizes: ["Normal", "Eléctrica"],
      },
      {
        id: "autoperfurantes",
        name: "Autoperfurantes",
        description: "Parafusos autoperfurantes para fixação de chapas e perfis.",
        image: "/images/autoperfurante.jpeg",
        unit: "un",
        group: "Fixações e Ferragens",
        sizes: ["Grandes", "Pequenos"],
      },
      {
        id: "carros-mao",
        name: "Carros de Mão",
        description: "Carros de mão para transporte de materiais em obra.",
        image: "/images/carrodemao.jpeg",
        unit: "un",
        group: "Fixações e Ferragens",
        sizes: ["Standard"],
      },
      {
        id: "disco-inox",
        name: "Disco Inox",
        description: "Disco de corte em inox para rebarbadora.",
        image: "/images/discoinox.jpeg",
        unit: "un",
        group: "Fixações e Ferragens",
        sizes: ["Standard"],
      },
      {
        id: "eletrodos",
        name: "Eléctrodos",
        description: "Eléctrodos de soldadura para soldadura por arco.",
        image: "/images/eletrodos.jpeg",
        unit: "un",
        group: "Fixações e Ferragens",
        sizes: ["2,5 mm", "3,0 mm"],
      },
      {
        id: "esferas",
        name: "Esferas",
        description: "Esferas de aço para decoração e ponteiras.",
        image: "/images/esferas.jpeg",
        unit: "un",
        group: "Fixações e Ferragens",
        sizes: ["Ø25 mm"],
      },
      {
        id: "pregos",
        name: "Pregos",
        description: "Pregos para fixação em obras e trabalhos gerais.",
        image: "/images/pregos.jpeg",
        unit: "kg",
        group: "Fixações e Ferragens",
        sizes: ["Standard"],
      },
      {
        id: "pas-de-bico-dkv",
        name: "Pás de Bico DKV",
        description: "Pás de bico DKV para apoio a trabalhos em obra.",
        image: "/images/pasdebicobkv.jpeg",
        unit: "un",
        group: "Fixações e Ferragens",
        sizes: ["Standard"],
      },
    ],
  },
];

export const SERVICES: ServiceItem[] = [
  {
    id: "corte-jato-agua",
    name: "Corte de Chapa a Jato de Água",
    description: "Corte de chapa a jato de água com elevada precisão para peças técnicas, peças por medida e trabalhos específicos.",
    image: "/imagensferros/machinerycloseup.jpeg",
    priceNote: "Preço mediante orçamento",
    highlight: "Ideal para cortes técnicos com acabamento limpo e adaptação ao desenho do cliente.",
  },
  {
    id: "bascula-pesagem",
    name: "Báscula para Pesagem",
    description: "Serviço de pesagem em báscula para cargas, viaturas e materiais, com apoio ao controlo logístico e operacional.",
    image: "/images/pesagem-servicos.jpeg",
    priceNote: "Serviço disponível sob consulta",
    highlight: "Limite de peso: 60000 kg",
  },
];

// Flat list gerado automaticamente do CATALOG (compatibilidade)
export const PRODUCTS = CATALOG.flatMap(cat =>
  cat.subcategories.map(sub => ({
    id: sub.id,
    name: sub.name,
    description: sub.description,
    image: sub.image,
    category: cat.name,
    categoryId: cat.id,
    sizes: sub.sizes,
    unit: sub.unit,
  }))
);
